//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1


use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "api_key_rate_limits")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub api_key_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::api_keys::Entity",
        from = "Column::ApiKeyId",
        to = "super::api_keys::Column::ApiKeyId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ApiKeys,
    #[sea_orm(
        belongs_to = "super::rate_limit_policies::Entity",
        from = "Column::PolicyId",
        to = "super::rate_limit_policies::Column::PolicyId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RateLimitPolicies,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::rate_limit_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RateLimitPolicies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
