//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod api_key_rate_limits;
pub mod api_keys;
pub mod audit_logs;
pub mod email_verification_tokens;
pub mod identity_providers;
pub mod impersonation_logs;
pub mod login_attempts;
pub mod metrics_events;
pub mod mfa_devices;
pub mod org_login_methods;
pub mod organizations;
pub mod password_reset_tokens;
pub mod permissions;
pub mod rate_limit_assignments;
pub mod rate_limit_counters;
pub mod rate_limit_policies;
pub mod role_inheritance;
pub mod role_permissions;
pub mod roles;
pub mod scim_clients;
pub mod scim_mappings;
pub mod scim_tokens;
pub mod sessions;
pub mod user_organization_info;
pub mod user_roles;
pub mod users;
pub mod waitlist_signups;
