//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::{
    api_key_rate_limits::Entity as ApiKeyRateLimits, api_keys::Entity as ApiKeys,
    audit_logs::Entity as AuditLogs, email_verification_tokens::Entity as EmailVerificationTokens,
    identity_providers::Entity as IdentityProviders, impersonation_logs::Entity as ImpersonationLogs,
    login_attempts::Entity as LoginAttempts, metrics_events::Entity as MetricsEvents,
    mfa_devices::Entity as MfaDevices, org_login_methods::Entity as OrgLoginMethods,
    organizations::Entity as Organizations, password_reset_tokens::Entity as PasswordResetTokens,
    permissions::Entity as Permissions, rate_limit_assignments::Entity as RateLimitAssignments,
    rate_limit_counters::Entity as RateLimitCounters, rate_limit_policies::Entity as RateLimitPolicies,
    role_inheritance::Entity as RoleInheritance, role_permissions::Entity as RolePermissions,
    roles::Entity as Roles, scim_clients::Entity as ScimClients, scim_mappings::Entity as ScimMappings,
    scim_tokens::Entity as ScimTokens, sessions::Entity as Sessions,
    user_organization_info::Entity as UserOrganizationInfo, user_roles::Entity as UserRoles,
    users::Entity as Users, waitlist_signups::Entity as WaitlistSignups,
};
