//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1


use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "scim_clients")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub client_id: Uuid,
    pub org_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub client_secret: String,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub enabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::OrgId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::scim_mappings::Entity")]
    ScimMappings,
    #[sea_orm(has_many = "super::scim_tokens::Entity")]
    ScimTokens,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::scim_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScimMappings.def()
    }
}

impl Related<super::scim_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScimTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
