# sesame-idam Development Environment
# Auto-generated by photon — do not edit manually

allow_k8s_contexts(['kind-sesame-idam'])

update_settings(k8s_upsert_timeout_secs=60)

docker_prune_settings(
    disable=False,
    max_age_mins=30,
    keep_recent=1,
    interval_hrs=1
)

config.define_string('tilt_port', args=False, usage='Port for Tilt web UI')
cfg = config.parse()
tilt_port = cfg.get('tilt_port', '10350')
os.putenv('TILT_PORT', tilt_port)

_brrtrouter_env = os.getenv('BRRTROUTER_ROOT', '').strip().rstrip('/')
brrtrouter_root = _brrtrouter_env if _brrtrouter_env else 'BRRTRouter'

_brrtrouter_venv_env = os.getenv('BRRTROUTER_VENV', '').strip().rstrip('/')
_home = os.getenv('HOME', '') or os.getenv('USERPROFILE', '')
brrtrouter_venv = _brrtrouter_venv_env if _brrtrouter_venv_env else (_home + '/.local/share/brrtrouter/venv' if _home else '.local/share/brrtrouter/venv')
sesame-idam_bin = 'sesame-idam/bin/sesame-idam' % brrtrouter_venv
sesame-idam_gen_bin = 'sesame-idam/target/debug/brrtrouter-gen' % brrtrouter_root
brrtrouter_bin = sesame-idam_bin
brrtrouter_gen_bin = sesame-idam_gen_bin

TOOLING_IGNORE = [
    '**/*.pyc',
    '**/*.pyo',
    '**/__pycache__',
    '**/.pytest_cache',
    '**/.coverage',
    '**/.coverage.*',
    '**/htmlcov',
    '**/coverage.xml',
    '**/.ruff_cache',
    '**/.mypy_cache',
    '**/*.egg',
    '**/*.egg-info',
    '**/*.egg-info/**',
    '**/brrtrouter_tooling.egg-info/**',
    '**/*_tooling.egg-info/**',
    '**/build',
    '**/build/**',
    '**/.hypothesis',
    '**/.DS_Store',
]

local_resource(
    'build-tooling',
    '''
set -e
VENV="home/casibbald/.local/.local/share/brrtrouter/venv"
BRRROOT="/home/casibbald/Workspace/microscaler/BRRTRouter"
test -d "$VENV" || python3 -m venv "$VENV"
"$VENV/bin/pip" install -U pip
"$VENV/bin/pip" install -e "$BRRROOT/tooling[dev]"
cd tooling && "$VENV/bin/pip" install -e '[dev]'
    '''
    deps=[
        './tooling/pyproject.toml',
        'BRRTRouter/tooling/pyproject.toml' %% brrtrouter_root,
    ],
    ignore=TOOLING_IGNORE,
    labels=['tooling'],
    allow_parallel=True,
)

k8s_yaml(kustomize('./k8s/data'))
k8s_yaml(kustomize('./k8s/microservices'))

# === Service Discovery ===

def _unquote(val):
    val = val.strip()
    if (val.startswith('"') and val.endswith('"')) or (val.startswith(''') and val.endswith(''')):
        return val[1:-1]
    return val

def _parse_bff_suite_config(path):
    content = str(read_file(path))
    services = []
    service_ports = {}
    service_spec_paths = {}
    bff_service_name = 'bff'
    in_services = False
    current = None

    for raw in content.split('\\n'):
        stripped = raw.strip()
        if not stripped or stripped.startswith('#'):
            continue

        if stripped.startswith('bff_service_name:'):
            bff_service_name = _unquote(stripped.split(':', 1)[1])
            continue

        if stripped == 'services:':
            in_services = True
            current = None
            continue

        if in_services and not raw.startswith('  '):
            in_services = False
            current = None

        if not in_services:
            continue

        if raw.startswith('  ') and not raw.startswith('    ') and stripped.endswith(':'):
            current = stripped[:-1]
            services.append(current)
            continue

        if current and raw.startswith('    ') and stripped.startswith('port:'):
            service_ports[current] = _unquote(stripped.split(':', 1)[1])
            continue

        if current and raw.startswith('    ') and stripped.startswith('spec_path:'):
            service_spec_paths[current] = _unquote(stripped.split(':', 1)[1])
            continue

    return {
        'bff_service_name': bff_service_name,
        'services': services,
        'ports': service_ports,
        'spec_paths': service_spec_paths,
    }

SUITE_CONFIG = _parse_bff_suite_config('openapi/idam/bff-suite-config.yaml')
DISCOVERED_IDAM_SERVICES = SUITE_CONFIG['services']
IDAM_PORTS = SUITE_CONFIG['ports']
IDAM_SPEC_PATHS = SUITE_CONFIG['spec_paths']
IDAM_BFF_NAME = SUITE_CONFIG['bff_service_name']

def _apply_port_overrides(config: dict) -> None:
    """Overlay port assignments from JSON config onto YAML-discovered ports."""
    svc_overrides = config.get('services', [])
    if not svc_overrides:
        return
    svc_map = {s['name']: s for s in svc_overrides}
    for svc_name in IDAM_PORTS:
        if svc_name in svc_map:
            override_port = svc_map[svc_name].get('port')
            if override_port and override_port != IDAM_PORTS[svc_name]:
                IDAM_PORTS[svc_name] = override_port

_apply_port_overrides(config)

def _runtime_ready_service(name):
    return str(local('test -d ./microservices/idam/$_s/gen/src && test -d ./microservices/idam/$_s/impl/src && echo yes || true' % 'idam', quiet=True)).strip() == 'yes'

_IDAM_SERVICES_READY = []
_IDAM_SERVICES_CONTRACT = []
for _s in DISCOVERED_IDAM_SERVICES:
    if _runtime_ready_service(_s):
        _IDAM_SERVICES_READY.append(_s)
    else:
        _IDAM_SERVICES_CONTRACT.append(_s)

print("sesame-idam Tilt discovered %d %s service contracts from %s" %% (len(DISCOVERED_IDAM_SERVICES), "IDAM", "idam", SUITE_CONFIG))
print("sesame-idam Tilt runtime-ready %s services: %s" %% (len(_IDAM_SERVICES_READY), ", ".join(_IDAM_SERVICES_READY)))
if _IDAM_SERVICES_CONTRACT:
    print("sesame-idam Tilt contract-only %s services skipped: %s" %% ("idam", ", ".join(_IDAM_SERVICES_CONTRACT)))

# === Helper functions ===

def get_service_port(name):
    if name in IDAM_PORTS:
        return IDAM_PORTS[name]
    return '8080'

def get_package_name(name):
    fallback_pkg = 'rerp_idam_' % ('idam') + name.replace('-', '_')
    manifest = 'microservices/idam/%s/impl/Cargo.toml' % name
    if str(local('test -e \"%s\" && echo yes || true' % manifest, quiet=True)).strip() != 'yes':
        return fallback

    content = str(read_file(manifest))
    in_package = False
    for raw in content.split('\\n'):
        stripped = raw.strip()
        if stripped == '[package]':
            in_package = True
            continue
        if stripped.startswith('[') and stripped != '[package]':
            in_package = False
            continue
        if in_package and stripped.startswith("name = "):
            return stripped.split('=', 1)[1].strip().strip('"').strip(''')
    return fallback

def create_microservice_lint(name, spec_file):
    local_resource(
        '%s-lint' % name,
        cmd='''
            set -e
            echo "🔍 Linting %s OpenAPI spec..." % name
            sesame-idam_bin lint \"
                --spec ./openapi/idam/%s \" % (spec_file, spec_file)
                --fail-on-error || \
            cargo run --manifest-path brrtrouter_root/Cargo.toml --bin brrtrouter-gen -- \
                lint \
                --spec ./openapi/idam/%s \" % (spec_file, spec_file)
                --fail-on-error
            echo "✅ %s OpenAPI spec linting passed" % name
        '''
        deps=['./openapi/%s/%s' % (suite, spec_file)],
        resource_deps=[],
        labels=['sesame-idam_' + name],
        allow_parallel=True,
    )

def create_microservice_gen(name, spec_file, output_dir):
    local_resource(
        '%s-service-gen' % name,
        cmd='sesame-idam gen suite idam --service name'
        deps=[
            './openapi/%s/%s' % (suite, spec_file),
            'tooling/pyproject.toml',
        ],
        ignore=[
            './microservices/idam/%s/gen/src' % name,
            './microservices/idam/%s/gen/doc' % name,
            './microservices/idam/%s/impl/config' % name,
            './microservices/idam/%s/gen/static_site' % name,
        ],
        resource_deps=['%s-lint' % name],
        labels=['sesame-idam_' + name],
        allow_parallel=True,
    )

def create_microservice_build_resource(name):
    local_resource(
        'build-%s' % name,
        cmd='sesame-idam build microservice name'
        deps=[
            './microservices/idam/%s/gen/Cargo.toml' % name,
            './microservices/idam/%s/impl/Cargo.toml' % name,
            './microservices/idam/%s/gen/src' % name,
            './microservices/idam/%s/impl/src' % name,
            'tooling/pyproject.toml',
        ],
        ignore=[
            './microservices/target',
            './build_artifacts',
        ],
        resource_deps=['sesame-idam-idam-all-gens']
        labels=['sesame-idam_' + name],
        allow_parallel=True,
    )

def create_microservice_deployment(name):
    package_name = get_package_name(name)
    binary_name = name.replace('-', '_')
    target_path = 'microservices/target/x86_64-unknown-linux-musl/debug/%s' % package_name
    artifact_path = 'build_artifacts/%s' % binary_name
    image_name = 'localhost:5001/sesame-idam--%s' % name
    port = get_service_port(name)

    hash_path = 'build_artifacts/%s.sha256' % binary_name
    local_resource(
        'copy-%s' % name,
        cmd='sesame-idam docker copy-binary target_path artifact_path binary_name'
        deps=[target_path, 'tooling/pyproject.toml'],
        resource_deps=['build-%s' % name],
        labels=['sesame-idam_' + name],
        allow_parallel=True,
    )

    local_resource(
        'docker-%s' % name,
        cmd='sesame-idam docker build-image-simple image_name hash_path artifact_path --service name'
        deps=[hash_path, artifact_path, 'docker/microservices/Dockerfile.template', 'tooling/pyproject.toml'],
        resource_deps=['copy-%s' % name],
        labels=['sesame-idam_' + name],
        allow_parallel=False,
    )

    k8s_yaml(helm('helm/sesame-idam-microservice' % 'helm/sesame-idam-microservice', name=name, namespace='sesame-idam', values=['helm/sesame-idam-microservice/values/helm/sesame-idam-microservice.yaml' % ('name', name)]))

    k8s_resource(
        name,
        port_forwards=['%s:%s' % (port, port)],
        resource_deps=['sesame-idam-database-env', 'docker-name'],
        labels=['sesame-idam_' + name],
        auto_init=True,
    )

# === Service Code Generation ===

local_resource(
    'sesame-idam-idam-all-gens' % pname,
    "echo \"sesame-idam All idam codegen complete\"" % pname,
    resource_deps=['%s-service-gen' % name for name in DISCOVERED_IDAM_SERVICES],
    labels=['sesame-idam_all_gens']
    allow_parallel=False,
)

for name in DISCOVERED_IDAM_SERVICES:
    service_spec_file = 'idam/%s' % IDAM_SPEC_PATHS.get(name, '%s/openapi.yaml' % name)
    create_microservice_lint(name, service_spec_file)
    create_microservice_gen(name, service_spec_file, name)
    create_microservice_build_resource(name)
    create_microservice_deployment(name)

