-- Dev seed — NOT generated by lifeguard-migrate. Idempotent.
-- Demo organizations + memberships for the hauliage tenant (FR-Demo-03/04).
-- Org UUIDs are shared with hauliage company `organization_profiles`
-- (domain profile keyed by the same UUID as Sesame org_id):
--   b2000001-… Transport Services (HAULIER)
--   b2000002-… AME Corp (SHIPPER)
-- Memberships make demo logins carry `org_id` in the JWT
-- (identity-login-service org_context::resolve_active_org_id).
-- Apply after Lifeguard migrations and the demo users seed.

INSERT INTO sesame_idam.organizations
    (id, name, tenant_id, status, created_at, updated_at)
VALUES
    (
        'b2000001-0001-4000-8000-000000000001',
        'Transport Services',
        'hauliage',
        'active',
        NOW(),
        NOW()
    ),
    (
        'b2000002-0002-4000-8000-000000000002',
        'AME Corp',
        'hauliage',
        'active',
        NOW(),
        NOW()
    )
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    tenant_id = EXCLUDED.tenant_id,
    status = EXCLUDED.status,
    updated_at = NOW();

-- role/status values follow org_lifecycle.rs conventions ('owner', 'active').
INSERT INTO sesame_idam.org_memberships
    (id, org_id, user_id, role, status, created_at, updated_at)
VALUES
    -- owner@hauliage.dev → Transport Services (legacy default persona)
    (
        'c3000001-0001-4000-8000-000000000001',
        'b2000001-0001-4000-8000-000000000001',
        'a1000001-0001-4000-8000-000000000001',
        'owner',
        'active',
        NOW(),
        NOW()
    ),
    -- dispatcher@hauliage.dev → Transport Services
    (
        'c3000001-0001-4000-8000-000000000002',
        'b2000001-0001-4000-8000-000000000001',
        'a1000001-0001-4000-8000-000000000002',
        'dispatcher',
        'active',
        NOW(),
        NOW()
    ),
    -- driver@hauliage.dev → Transport Services
    (
        'c3000001-0001-4000-8000-000000000003',
        'b2000001-0001-4000-8000-000000000001',
        'a1000001-0001-4000-8000-000000000003',
        'driver',
        'active',
        NOW(),
        NOW()
    ),
    -- shipper@amecorp.dev → AME Corp (SHIPPER persona, OWNER of own org)
    (
        'c3000001-0001-4000-8000-000000000004',
        'b2000002-0002-4000-8000-000000000002',
        'a1000001-0001-4000-8000-000000000004',
        'owner',
        'active',
        NOW(),
        NOW()
    ),
    -- transport@transportservices.dev → Transport Services (HAULIER persona)
    (
        'c3000001-0001-4000-8000-000000000005',
        'b2000001-0001-4000-8000-000000000001',
        'a1000001-0001-4000-8000-000000000005',
        'owner',
        'active',
        NOW(),
        NOW()
    )
ON CONFLICT (id) DO UPDATE SET
    org_id = EXCLUDED.org_id,
    user_id = EXCLUDED.user_id,
    role = EXCLUDED.role,
    status = EXCLUDED.status,
    updated_at = NOW();
