apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/part-of: sesame-idam
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service.name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
