// ⚠️ WARNING: This file is auto-generated by BRRTRouter for the **impl** crate
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next `brrtrouter-gen generate-stubs`
// ⚠️ Business logic belongs in impl/src/controllers/<operationId>.rs (user-owned)
//
// ADR 0001 Layer 2: `register_impl` overrides gen mock handlers for controllers
// discovered on disk. The gen crate's `registry.rs` (`register_from_spec`) runs first;
// this module replaces matching routes with impl controllers.
//
// NOT the same as:
//   - gen/src/registry.rs        (template: registry.rs.txt — mock layer)
//   - cylon-skills registry.rs   (unrelated skills/personalities JSON index)

use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed_with_stack_size_and_name;

/// Register impl controllers discovered on disk (overrides gen stubs per ADR 0001 Layer 2).
///
/// # Safety
/// Spawns handler coroutines. Callers must ensure the coroutine runtime is initialized.
pub unsafe fn register_impl(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    for route in routes {
        match route.handler_name.as_ref() {
            "accept_invitation" => {
                if let Ok(tx) = brrtrouter::dispatcher::spawn_untyped_with_stack_size_and_name(
                    |req| crate::controllers::accept_invitation::handle(req),
                    20480,
                    Some(route.handler_name.as_ref()),
                ) {
                    dispatcher.add_route(route.clone(), tx);
                }
            }
            "add_user_to_org" => {
                if let Ok(tx) = brrtrouter::dispatcher::spawn_untyped_with_stack_size_and_name(
                    |req| crate::controllers::add_user_to_org::handle(req),
                    20480,
                    Some(route.handler_name.as_ref()),
                ) {
                    dispatcher.add_route(route.clone(), tx);
                }
            }
            "create_organization" => {
                if let Ok(tx) = brrtrouter::dispatcher::spawn_untyped_with_stack_size_and_name(
                    |req| crate::controllers::create_organization::handle(req),
                    20480,
                    Some(route.handler_name.as_ref()),
                ) {
                    dispatcher.add_route(route.clone(), tx);
                }
            }
            "invite_user_to_org" => {
                if let Ok(tx) = brrtrouter::dispatcher::spawn_untyped_with_stack_size_and_name(
                    |req| crate::controllers::invite_user_to_org::handle(req),
                    20480,
                    Some(route.handler_name.as_ref()),
                ) {
                    dispatcher.add_route(route.clone(), tx);
                }
            }
            "list_my_memberships" => {
                if let Ok(tx) = brrtrouter::dispatcher::spawn_untyped_with_stack_size_and_name(
                    |req| crate::controllers::list_my_memberships::handle(req),
                    20480,
                    Some(route.handler_name.as_ref()),
                ) {
                    dispatcher.add_route(route.clone(), tx);
                }
            }
            _ => {}
        }
    }
}
