-- Dev seed — NOT generated by lifeguard-migrate. Idempotent.
-- Demo user for the PriceWhisperer tenant (CRM demo, 2026-09-04). Mirrors the
-- acme demo-users convention. The pricewhisperer tenant + this user may also be
-- provisioned at runtime, so every statement is guarded and skips if present
-- (it never clobbers an existing user's password or id).
--
-- Password (fresh DBs only): SecureP@ss123!  (argon2id hash below, same as the
-- acme demo users). Apply after Lifeguard migrations.

INSERT INTO sesame_idam.users
    (id, email, password_hash, tenant_id, status, email_verified, phone, phone_verified, created_at, updated_at)
SELECT
    'a2000010-0010-4000-8000-000000000001',
    'demo-trader@pricewhisperer.dev',
    '$argon2id$v=19$m=19456,t=2,p=1$eLP8jC1l/A/lL9DP6A86eg$xlODypgdg/4v+VvL/aNJ91YM777HmbiErxcMX9W+2bo',
    'pricewhisperer',
    'active',
    true,
    NULL,
    false,
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM sesame_idam.users
    WHERE email = 'demo-trader@pricewhisperer.dev' AND tenant_id = 'pricewhisperer'
);

-- Product profile (display name) for the demo user, so the trader portal shows
-- a real name rather than the bare email. Keyed off the user row above.
INSERT INTO sesame_idam.user_profiles
    (id, user_id, first_name, last_name, avatar_url, created_at, updated_at)
SELECT
    'a2000011-0011-4000-8000-000000000001', u.id, 'Demo', 'Trader', NULL, NOW(), NOW()
FROM sesame_idam.users u
WHERE u.email = 'demo-trader@pricewhisperer.dev' AND u.tenant_id = 'pricewhisperer'
  AND NOT EXISTS (
    SELECT 1 FROM sesame_idam.user_profiles p WHERE p.user_id = u.id
  );
