-- Dev seed — NOT generated by lifeguard-migrate. Idempotent.
-- Demo users for the hauliage tenant (first client project).
-- Password for all demo users: SecureP@ss123!  (argon2id hash below)
-- Apply after Lifeguard migrations (sesame-idam-apply-migrations).

INSERT INTO sesame_idam.users
    (id, email, password_hash, tenant_id, status, email_verified, phone, phone_verified, created_at, updated_at)
VALUES
    (
        'a1000001-0001-4000-8000-000000000001',
        'owner@hauliage.dev',
        '$argon2id$v=19$m=19456,t=2,p=1$eLP8jC1l/A/lL9DP6A86eg$xlODypgdg/4v+VvL/aNJ91YM777HmbiErxcMX9W+2bo',
        'hauliage',
        'active',
        true,
        NULL,
        false,
        NOW(),
        NOW()
    ),
    (
        'a1000001-0001-4000-8000-000000000002',
        'dispatcher@hauliage.dev',
        '$argon2id$v=19$m=19456,t=2,p=1$eLP8jC1l/A/lL9DP6A86eg$xlODypgdg/4v+VvL/aNJ91YM777HmbiErxcMX9W+2bo',
        'hauliage',
        'active',
        true,
        NULL,
        false,
        NOW(),
        NOW()
    ),
    (
        'a1000001-0001-4000-8000-000000000003',
        'driver@hauliage.dev',
        '$argon2id$v=19$m=19456,t=2,p=1$eLP8jC1l/A/lL9DP6A86eg$xlODypgdg/4v+VvL/aNJ91YM777HmbiErxcMX9W+2bo',
        'hauliage',
        'active',
        true,
        NULL,
        false,
        NOW(),
        NOW()
    )
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    tenant_id = EXCLUDED.tenant_id,
    status = EXCLUDED.status,
    email_verified = EXCLUDED.email_verified,
    updated_at = NOW();
