//! Identity login service entity models
//!
//! Generated by Lifeguard ORM derive macros.
pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
pub mod magic_link_token;
pub mod otp_token;
pub mod refresh_token;
pub mod social_credential;
pub mod user;
