//! Identity login service entity models
//!
//! Generated by Lifeguard ORM derive macros.
pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
pub mod magic_link_token;
pub mod otp_token;
pub mod refresh_token;
pub mod relying_party_client;
pub mod relying_party_client_capability;
pub mod relying_party_client_redirect_uri;
pub mod relying_party_client_secret;
pub mod social_credential;
pub mod tenant;
pub mod tenant_oauth_provider;
pub mod tenant_sms_config;
pub mod user;
pub mod user_profile;
