-- Dev seed — NOT generated by lifeguard-migrate. Idempotent.
-- Platform tenant registry + OAuth metadata for SaaS-of-SaaS products.
-- Secrets live in K8s/env; this file only registers metadata + env key names.
-- Apply after Lifeguard migrations create `tenants` and `tenant_oauth_providers`.

INSERT INTO sesame_idam.tenants
    (id, slug, display_name, status, provisioning_mode, created_at, updated_at)
VALUES
    (
        'a1000001-0001-4000-8000-000000000001',
        'acme',
        'Acme',
        'active',
        'platform',
        NOW(),
        NOW()
    ),
    (
        'a1000002-0002-4000-8000-000000000002',
        'globex',
        'Globex',
        'active',
        'platform',
        NOW(),
        NOW()
    )
ON CONFLICT (slug) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    status = EXCLUDED.status,
    provisioning_mode = EXCLUDED.provisioning_mode,
    updated_at = NOW();

-- First-party relying parties. client_id is public and globally unique; it
-- selects tenant/application context but grants no authority by itself.
INSERT INTO sesame_idam.relying_party_clients
    (id, client_id, tenant_slug, portal, application_id, client_type,
     token_endpoint_auth_method, pkce_s256_required, authority_class,
     status, created_at, updated_at)
VALUES
    (
        'a1500001-0001-4000-8000-000000000001',
        'acme-web',
        'acme',
        'frontend',
        'frontend',
        'confidential',
        'client_secret_basic',
        FALSE,
        'tenant',
        'active',
        NOW(),
        NOW()
    )
ON CONFLICT (client_id) DO UPDATE SET
    tenant_slug = EXCLUDED.tenant_slug,
    portal = EXCLUDED.portal,
    application_id = EXCLUDED.application_id,
    status = EXCLUDED.status,
    updated_at = NOW();

INSERT INTO sesame_idam.relying_party_client_redirect_uris
    (id, relying_party_client_id, kind, uri, created_at)
VALUES
    (
        'a1500001-0002-4000-8000-000000000001',
        'a1500001-0001-4000-8000-000000000001',
        'login',
        'https://app.example.com/auth/callback',
        NOW()
    ),
    (
        'a1500001-0002-4000-8000-000000000002',
        'a1500001-0001-4000-8000-000000000001',
        'post_logout',
        'https://app.example.com/',
        NOW()
    )
ON CONFLICT (relying_party_client_id, kind, uri) DO NOTHING;

INSERT INTO sesame_idam.relying_party_client_capabilities
    (id, relying_party_client_id, kind, value, created_at)
SELECT gen_random_uuid(), 'a1500001-0001-4000-8000-000000000001', kind, value, NOW()
FROM (
    VALUES
        ('grant', 'authorization_code'),
        ('grant', 'refresh_token'),
        ('response_type', 'code'),
        ('scope', 'openid'),
        ('scope', 'profile'),
        ('scope', 'email'),
        ('audience', 'sesame-idam')
) AS capability(kind, value)
ON CONFLICT (relying_party_client_id, kind, value) DO NOTHING;

-- Google OAuth metadata (secrets via env keys — K8s secrets in dev/prod).
INSERT INTO sesame_idam.tenant_oauth_providers
    (id, tenant_slug, provider, client_id, redirect_uris, secret_env_key,
     client_id_env_key, config_version, last_rotated_at, last_rotated_by,
     enabled, created_at, updated_at)
VALUES
    (
        'a2000001-0001-4000-8000-000000000001',
        'acme',
        'google',
        'placeholder-acme-google-client-id',
        'http://app.example.com/oauth/callback,http://localhost:7174/oauth/callback',
        'SESAME_OAUTH__ACME__GOOGLE_CLIENT_SECRET',
        'SESAME_OAUTH__ACME__GOOGLE_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'a2000002-0002-4000-8000-000000000002',
        'acme',
        'microsoft',
        'placeholder-acme-microsoft-client-id',
        'http://app.example.com/oauth/callback,http://localhost:7174/oauth/callback',
        'SESAME_OAUTH__ACME__MICROSOFT_CLIENT_SECRET',
        'SESAME_OAUTH__ACME__MICROSOFT_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'a2000003-0003-4000-8000-000000000003',
        'globex',
        'google',
        'placeholder-globex-google-client-id',
        'http://globex.example.com/oauth/callback',
        'SESAME_OAUTH__GLOBEX__GOOGLE_CLIENT_SECRET',
        'SESAME_OAUTH__GLOBEX__GOOGLE_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'a2000004-0004-4000-8000-000000000004',
        'globex',
        'microsoft',
        'placeholder-globex-microsoft-client-id',
        'http://globex.example.com/oauth/callback',
        'SESAME_OAUTH__GLOBEX__MICROSOFT_CLIENT_SECRET',
        'SESAME_OAUTH__GLOBEX__MICROSOFT_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    )
ON CONFLICT (tenant_slug, provider) DO UPDATE SET
    client_id = EXCLUDED.client_id,
    redirect_uris = EXCLUDED.redirect_uris,
    secret_env_key = EXCLUDED.secret_env_key,
    client_id_env_key = EXCLUDED.client_id_env_key,
    enabled = EXCLUDED.enabled,
    updated_at = NOW();
