-- Dev seed — NOT generated by lifeguard-migrate. Idempotent.
-- Platform tenant registry + OAuth metadata for SaaS-of-SaaS products.
-- Secrets live in K8s/env; this file only registers metadata + env key names.
-- Apply after Lifeguard migrations create `tenants` and `tenant_oauth_providers`.

INSERT INTO sesame_idam.tenants
    (id, slug, display_name, status, provisioning_mode, created_at, updated_at)
VALUES
    (
        'a1000001-0001-4000-8000-000000000001',
        'hauliage',
        'Hauliage',
        'active',
        'platform',
        NOW(),
        NOW()
    ),
    (
        'a1000002-0002-4000-8000-000000000002',
        'pricewhisperer',
        'PriceWhisperer',
        'active',
        'platform',
        NOW(),
        NOW()
    )
ON CONFLICT (slug) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    status = EXCLUDED.status,
    provisioning_mode = EXCLUDED.provisioning_mode,
    updated_at = NOW();

-- Google OAuth metadata (secrets via env keys — K8s secrets in dev/prod).
INSERT INTO sesame_idam.tenant_oauth_providers
    (id, tenant_slug, provider, client_id, redirect_uris, secret_env_key,
     client_id_env_key, config_version, last_rotated_at, last_rotated_by,
     enabled, created_at, updated_at)
VALUES
    (
        'a2000001-0001-4000-8000-000000000001',
        'hauliage',
        'google',
        'placeholder-hauliage-google-client-id',
        'http://hauliage.dev.microscaler.local/oauth/callback,http://localhost:7174/oauth/callback',
        'SESAME_OAUTH__HAULIAGE__GOOGLE_CLIENT_SECRET',
        'SESAME_OAUTH__HAULIAGE__GOOGLE_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'a2000002-0002-4000-8000-000000000002',
        'hauliage',
        'microsoft',
        'placeholder-hauliage-microsoft-client-id',
        'http://hauliage.dev.microscaler.local/oauth/callback,http://localhost:7174/oauth/callback',
        'SESAME_OAUTH__HAULIAGE__MICROSOFT_CLIENT_SECRET',
        'SESAME_OAUTH__HAULIAGE__MICROSOFT_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'a2000003-0003-4000-8000-000000000003',
        'pricewhisperer',
        'google',
        'placeholder-pw-google-client-id',
        'http://pricewhisperer.dev.microscaler.local/oauth/callback',
        'SESAME_OAUTH__PRICEWHISPERER__GOOGLE_CLIENT_SECRET',
        'SESAME_OAUTH__PRICEWHISPERER__GOOGLE_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'a2000004-0004-4000-8000-000000000004',
        'pricewhisperer',
        'microsoft',
        'placeholder-pw-microsoft-client-id',
        'http://pricewhisperer.dev.microscaler.local/oauth/callback',
        'SESAME_OAUTH__PRICEWHISPERER__MICROSOFT_CLIENT_SECRET',
        'SESAME_OAUTH__PRICEWHISPERER__MICROSOFT_CLIENT_ID',
        1,
        NULL,
        NULL,
        TRUE,
        NOW(),
        NOW()
    )
ON CONFLICT (tenant_slug, provider) DO UPDATE SET
    client_id = EXCLUDED.client_id,
    redirect_uris = EXCLUDED.redirect_uris,
    secret_env_key = EXCLUDED.secret_env_key,
    client_id_env_key = EXCLUDED.client_id_env_key,
    enabled = EXCLUDED.enabled,
    updated_at = NOW();
