-- Dev seed — NOT generated by lifeguard-migrate. Idempotent.
-- CRM demo access for the PriceWhisperer tenant (2026-09-04): grants
-- demo-trader the crm.editor role. The RERP crm/pipeline service authorises
-- reads with crm.viewer|crm.editor and mutations with crm.editor, scoped to
-- tenant `pricewhisperer` (see rerp crm/pipeline impl/src/auth.rs).
--
-- Keyed by email rather than a fixed principal id, so it also covers a
-- demo-trader that was provisioned at runtime (its user id differs from the
-- seed's). Apply AFTER the pricewhisperer demo-users seed.

INSERT INTO sesame_idam.role_assignments
    (id, principal_id, role_name, resource_type, resource_id, tenant_id, created_at, updated_at)
SELECT
    gen_random_uuid(), u.id, 'crm.editor', 'application', NULL, 'pricewhisperer', NOW(), NOW()
FROM sesame_idam.users u
WHERE u.email = 'demo-trader@pricewhisperer.dev' AND u.tenant_id = 'pricewhisperer'
  AND NOT EXISTS (
    SELECT 1 FROM sesame_idam.role_assignments ra
    WHERE ra.principal_id = u.id
      AND ra.role_name = 'crm.editor'
      AND ra.tenant_id = 'pricewhisperer'
  );
