-- Dev seed — NOT generated by lifeguard-migrate. Idempotent.
-- Role assignments for the hauliage demo users (see
-- identity-user-mgmt-service/impl/seeds/20260706000000_hauliage_demo_users.sql).
-- Roles follow hauliage's RBAC model: OWNER | DISPATCHER | FLEET_MANAGER | DRIVER | VIEWER.
-- Apply after Lifeguard migrations and the demo users seed.

INSERT INTO sesame_idam.role_assignments
    (id, principal_id, role_name, resource_type, resource_id, tenant_id, created_at, updated_at)
VALUES
    (
        'b3000001-0001-4000-8000-000000000001',
        'a1000001-0001-4000-8000-000000000001', -- owner@hauliage.dev
        'OWNER',
        'application',
        NULL,
        'hauliage',
        NOW(),
        NOW()
    ),
    (
        'b3000001-0001-4000-8000-000000000002',
        'a1000001-0001-4000-8000-000000000002', -- dispatcher@hauliage.dev
        'DISPATCHER',
        'application',
        NULL,
        'hauliage',
        NOW(),
        NOW()
    ),
    (
        'b3000001-0001-4000-8000-000000000003',
        'a1000001-0001-4000-8000-000000000003', -- driver@hauliage.dev
        'DRIVER',
        'application',
        NULL,
        'hauliage',
        NOW(),
        NOW()
    )
ON CONFLICT (id) DO UPDATE SET
    role_name = EXCLUDED.role_name,
    tenant_id = EXCLUDED.tenant_id,
    updated_at = NOW();
