apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sesame-idam

configMapGenerator:
  - name: sesame-idam-database-config
    envs:
      - application.properties

secretGenerator:
  - name: sesame-idam-db-credentials
    envs:
      - application.secrets.env

generatorOptions:
  disableNameSuffixHash: true
  immutable: false
