apiVersion: v1
kind: Secret
metadata:
    name: sesame-idam-signing-keyset
    namespace: sesame-idam
    labels:
        app.kubernetes.io/part-of: sesame-idam
type: Opaque
stringData:
    signing-keyset.json: ENC[AES256_GCM,data:HJBJA5yfEV6FLyIDVjn4GpFF17UVpGRaqJzSqseVOtc84hZ0v3L/Mzuv83w3qGdaGLHZpJNnHastVForiEg0mNOBoZFFsxQSOs2MyFtLoKfhAkk0d3kJUyyMesriH8hmw8frvAjNF4OdUfR7eCsN7xNsMfI7hMaXwKoP3XTW8aQxOCtMqLZoCSjObWvX2ZH6/GHmx7xryA3HS5tBOCL5DY61BvzDSCS8ZseOCIHs5dajNRo8IP5Zqfq/vC0Ki+igoVXa4W0gmQAWQD1Zd33wzEP4OKGS0xo8RtcJG2JY067eGs/m5Fum5eZF/pTes+zVE2ldugGWkA8yjbq8cc3aVz4+ovbahOwZdnFujVLdYGcXuTnouN6FnSTUmxIaLtgDHsrHryrVfInbEMsru6OvXl6Yod0YxPiR1D5nWP804OHFSi5ZduzLGPACxn0Rh73ZXhF+YCM5JQQMmKG61DFdyp2dryu9hP2kBRjklAHTYn+DX0KQOKLhbv6t5TgbSepFLE7FAdrmEf5SLmjC1aN+,iv:78oxIXbe0EdvnXjNb41PBNlR2Q+CyC/Cvz4K/QC3u4s=,tag:cOwb0MAg6dAvL0HEYIEmpA==,type:str]
sops:
    age:
        - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dExhWXNlaTlHZ0lwTUlH
            d1dsQWpoakgxUmlaR0g5QkNuTlRWSVBPcEZFCk5uVy9vbWtRWVBQSERpUTRuVEZJ
            VWZHTm5aRU1YcGwrZ0ZFWWFZUmJ1ZzgKLS0tIG5qdzlmQnpEMmcwb2c3Vk1nenFY
            Q3UrUkFja1FpWXdNaVJnc1BsRUZZSzQK0fLF1gkc9lszcObWPk+YvAnInTDdzvZt
            XFCzJhdOc1/fHqo99CWO+eoWI+iTys2SPB2k0p70mHWl83W6TX4KEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rggv7pvzmhz2us64p4kmdxdwe49vru6ecnkgv6cx640jj87jev0s2uvuc9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTkZNbkw5L1d2dmJDZkVh
            RDdSVVlDS1R4cjZWY1JHejhUbXNuSUgvVXlvCjFoZjdIZWtTNnpCV0w0YnFrL3Zt
            VkhNRGcxNytyaExCeTZ3MkZ6aHdieEUKLS0tIHYvbjlqT2JkbHZSNENPVW1MSTFI
            RkltR2dkYzdXd1NGWjh5WGorTDVpdEUK6cZW8bNy4vktE8lYwFHwjnLgtZVLmGfA
            RUr8L1HRjVW/BDN5/ornrXLI2x6Z+FgdJF1ncUki2zS5/UCkppYmjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T17:13:02Z"
    mac: ENC[AES256_GCM,data:9hZ2dcBRVUPLFv2B/C8H0VviSICjXixhWgqYJc4D9jadTktpXJ2ZG/5C8km2cJxeNSBOjWMsdmF2/GGfQDOhjc877CRv6SpbND/JMacwsT/BAWtkq/jSXgK2DCf0dPs17QfmxD/9xGd0iNmgcc7ZSJ7uyqzNNS6ZdkDWa7c0504=,iv:gK8E5amq0jQKGQ5VTYbjyuE4K+YdbZq+A1n/cGNenAY=,tag:jfoZ8ZIWHjbtVyda6F4d/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
