-- Migration: permissions
-- Generated: 20260516192347

ALTER TABLE permissions ADD COLUMN IF NOT EXISTS action VARCHAR(255) NOT NULL;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS org_id UUID NOT NULL REFERENCES sesame_idam.organizations(id) ON DELETE CASCADE;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS resource VARCHAR(255) NOT NULL;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL;
