-- Migration: api_keys
-- Generated: 20260516192347

ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS org_id UUID REFERENCES sesame_idam.organizations(id) ON DELETE CASCADE;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS permissions TEXT;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255) NOT NULL;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL;
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES sesame_idam.users(id) ON DELETE CASCADE;
