apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authz-core
spec:
  interval: 5m
  timeout: 5m
  releaseName: authz-core
  targetNamespace: sesame-idam
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: ./helm/sesame-idam-microservice
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: product-sesame-idam
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: sesame-idam-idam-common-helm-values
      valuesKey: values.yaml
  values:
    service:
      name: authz-core
    image:
      name: sesame-idam-authz-core
      tag: dev-1784924047066010365 # {"$imagepolicy": "flux-system:sesame-idam-authz-core:tag"}
    app:
      binaryName: authz-core
      serviceName: authz-core
