# Sesame frontend: sesame-brochure → https://sesame-brochure.dev.microscaler.local  (ADR-010)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sesame-brochure
spec:
  interval: 5m
  timeout: 5m
  releaseName: sesame-brochure
  targetNamespace: sesame-idam
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: ./helm/sesame-idam-frontend
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: product-sesame-idam
        namespace: flux-system
      interval: 1m
  values:
    service:
      name: sesame-brochure
    image:
      name: sesame-idam-frontend-brochure
      tag: tilt # {"$imagepolicy": "flux-system:sesame-idam-frontend-brochure:tag"}
    route:
      enabled: true
      hostnames:
        - sesame-brochure.dev.microscaler.local

