service:
  name: authentication
  port: 8001
  containerPort: 8001
  nodePort: 30801
image:
  name: sesame-idam-authentication
  tag: tilt
deployment:
  namespace: sesame-idam
app:
  binaryName: authentication
  serviceName: authentication
